runtime: python311
service: default
instance_class: F1

entrypoint: gunicorn -b :$PORT ai_agent.wsgi:application --log-level info

# 자동 스케일링 설정
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

# 리소스 설정
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  DJANGO_SETTINGS_MODULE: "ai_agent.settings"
  PYTHONPATH: "/app"
  DB_HOST: "/cloudsql/library-ai-agent-kr:asia-northeast3:library-ai-db"
  DB_NAME: "library_ai_db"
  DB_USER: "postgres"
  DB_PASSWORD: "Library@AI2025!"

# .env 파일에서 환경 변수 로드
includes:
  - .env

# Cloud SQL 인스턴스 연결 설정
beta_settings:
  cloud_sql_instances: library-ai-agent-kr:asia-northeast3:library-ai-db

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always 