# Generated by Django 5.2 on 2025-04-18 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('title', models.CharField(max_length=200, verbose_name='리뷰 제목')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('is_verified', models.BooleanField(default=False, verbose_name='예매자 인증 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='공감수')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='data_analysis.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
