# Generated by Django 5.2 on 2025-04-18 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sales_data/%Y/%m/', verbose_name='판매현황 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='data_analysis.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '판매현황',
                'verbose_name_plural': '판매현황',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='settlement_data/%Y/%m/', verbose_name='정산서 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_data', to='data_analysis.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '정산서',
                'verbose_name_plural': '정산서',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
