# Generated by Django 5.2 on 2025-04-21 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_performance_running_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_calendar', to='data_analysis.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '마케팅 캘린더',
                'verbose_name_plural': '마케팅 캘린더',
            },
        ),
        migrations.CreateModel(
            name='MarketingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data_analysis.marketingcalendar', verbose_name='마케팅 캘린더')),
            ],
            options={
                'verbose_name': '마케팅 일정',
                'verbose_name_plural': '마케팅 일정',
                'ordering': ['date'],
            },
        ),
    ]
