# Generated by Django 5.2 on 2025-04-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0006_auto_20250421_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingevent',
            options={'ordering': ['start_date'], 'verbose_name': '마케팅 일정', 'verbose_name_plural': '마케팅 일정'},
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('positive', '긍정'), ('neutral', '중립'), ('negative', '부정')], default='neutral', max_length=10, verbose_name='감정 분석'),
        ),
    ]
