# Generated by Django 5.2 on 2025-04-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_alter_marketingevent_options_review_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='running_time',
            field=models.CharField(default='', help_text='150분, 2시간 30분', max_length=50, verbose_name='공연시간'),
        ),
    ]
