# Generated by Django 5.2 on 2025-04-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0008_alter_performance_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingevent',
            name='tag',
            field=models.CharField(choices=[('promotion', '프로모션'), ('marketing', '마케팅'), ('press', '언론보도'), ('event', '이벤트'), ('sns', 'SNS'), ('other', '기타')], default='promotion', max_length=20, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='running_time',
            field=models.CharField(default='', max_length=50, verbose_name='공연시간'),
        ),
    ]
