# Generated by Django 5.2 on 2025-04-21 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0010_alter_marketingevent_color_alter_marketingevent_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='크롤링할 플랫폼 이름을 입력하세요. (예: 인터파크티켓, 티켓링크, 인스타그램)', max_length=50, verbose_name='플랫폼')),
                ('url', models.URLField(help_text='크롤링할 페이지의 URL을 입력하세요.', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, help_text='크롤링 대상 활성화 여부를 설정합니다.', verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('last_crawled_at', models.DateTimeField(blank=True, help_text='가장 최근에 크롤링을 수행한 일시입니다.', null=True, verbose_name='마지막 크롤링 일시')),
                ('crawling_interval', models.PositiveIntegerField(default=24, help_text='크롤링을 수행할 주기를 시간 단위로 입력하세요.', verbose_name='크롤링 주기(시간)')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawling_targets', to='data_analysis.performance', verbose_name='공연')),
            ],
            options={
                'verbose_name': '크롤링 대상',
                'verbose_name_plural': '크롤링 대상 목록',
                'ordering': ['-created_at'],
                'unique_together': {('performance', 'platform', 'url')},
            },
        ),
    ]
