# Generated by Django 5.2 on 2025-04-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0011_crawlingtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingtarget',
            name='crawling_interval',
        ),
    ]
