# Generated by Django 5.0.2 on 2025-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0012_remove_crawlingtarget_crawling_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='genre',
            field=models.CharField(choices=[('concert', '콘서트'), ('musical', '뮤지컬'), ('play', '연극'), ('exhibition', '전시')], default='concert', max_length=20, verbose_name='장르'),
        ),
    ]
