# Generated by Django 5.0.2 on 2025-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0013_performance_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='객석 점유율'),
        ),
        migrations.AddField(
            model_name='performance',
            name='total_audience',
            field=models.PositiveIntegerField(default=0, verbose_name='총 관객수'),
        ),
        migrations.AddField(
            model_name='performance',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 매출'),
        ),
    ]
