# Generated by Django 5.0.2 on 2025-04-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0014_performance_occupancy_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='average_ticket_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='객단가'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='free_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='무료 점유율'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='paid_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='유료 점유율'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='목표 매출'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 매출액'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='total_occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='전체 점유율'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='total_sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='총 판매량'),
        ),
    ]
