# Generated by Django 5.0.2 on 2025-04-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0015_salesdata_average_ticket_price_salesdata_free_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='description',
            field=models.TextField(blank=True, verbose_name='공연 설명'),
        ),
        migrations.AddField(
            model_name='performance',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터'),
        ),
        migrations.AddField(
            model_name='performance',
            name='status',
            field=models.CharField(choices=[('upcoming', '공연 예정'), ('ongoing', '공연 중'), ('completed', '공연 종료')], default='upcoming', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='age_limit',
            field=models.CharField(max_length=50, verbose_name='관람 연령'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_date',
            field=models.DateTimeField(verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='genre',
            field=models.CharField(choices=[('concert', '콘서트'), ('musical', '뮤지컬'), ('play', '연극'), ('exhibition', '전시')], max_length=20, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='running_time',
            field=models.CharField(max_length=50, verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_audience',
            field=models.IntegerField(default=0, verbose_name='총 관객수'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='총 매출'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='venue',
            field=models.CharField(max_length=200, verbose_name='공연장'),
        ),
    ]
