# Generated by Django 5.0.2 on 2025-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0016_performance_description_performance_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='status',
        ),
        migrations.AlterField(
            model_name='performance',
            name='age_limit',
            field=models.CharField(max_length=50, verbose_name='관람연령'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='end_date',
            field=models.DateField(verbose_name='공연 종료일'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='genre',
            field=models.CharField(choices=[('concert', '콘서트'), ('musical', '뮤지컬'), ('play', '연극'), ('exhibition', '전시')], default='concert', max_length=20, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='running_time',
            field=models.CharField(default='', max_length=50, verbose_name='공연시간'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='start_date',
            field=models.DateField(verbose_name='공연 시작일'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_audience',
            field=models.PositiveIntegerField(default=0, verbose_name='총 관객수'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='total_sales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='총 매출'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='venue',
            field=models.CharField(max_length=200, verbose_name='공연장소'),
        ),
    ]
