# Generated by Django 5.0.2 on 2025-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0017_remove_performance_poster_remove_performance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터'),
        ),
    ]
