# Generated by Django 5.0.2 on 2025-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0019_alter_crawlingtarget_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsummary',
            name='free_rate',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='occupancy_rate',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='paid_rate',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='target_revenue',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='total_seats_sold',
        ),
        migrations.RemoveField(
            model_name='sessionsummary',
            name='variance_revenue',
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='amount_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='금액 평균'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='r_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='R석 평균'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='r_count',
            field=models.PositiveIntegerField(null=True, verbose_name='R석 판매수'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='s_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='S석 평균'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='s_count',
            field=models.PositiveIntegerField(null=True, verbose_name='S석 판매수'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='total_amount',
            field=models.PositiveIntegerField(null=True, verbose_name='총 매출액'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='total_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='전체 평균'),
        ),
        migrations.AddField(
            model_name='sessionsummary',
            name='total_count',
            field=models.PositiveIntegerField(null=True, verbose_name='총 판매수'),
        ),
    ]
