# Generated by Django 5.0.2 on 2025-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0020_remove_sessionsummary_free_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='error_log',
            field=models.TextField(blank=True, verbose_name='오류 로그'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='파일 해시'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 시간'),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='status',
            field=models.CharField(choices=[('pending', '처리 대기'), ('processing', '처리 중'), ('done', '완료'), ('error', '오류')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='delta_revenue',
            field=models.BigIntegerField(default=0, verbose_name='증감(매출)'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='revenue_total',
            field=models.BigIntegerField(verbose_name='누적 매출'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='target_amount',
            field=models.BigIntegerField(default=0, verbose_name='목표 매출'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='total_amount',
            field=models.BigIntegerField(default=0, verbose_name='총 매출액'),
        ),
        migrations.AlterUniqueTogether(
            name='performancesession',
            unique_together={('performance', 'round_number'), ('performance', 'session_date', 'session_time')},
        ),
        migrations.AlterUniqueTogether(
            name='salesdata',
            unique_together={('performance', 'file_hash')},
        ),
        migrations.AddIndex(
            model_name='dailysales',
            index=models.Index(fields=['performance', 'date'], name='data_analys_perform_2ec02a_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesession',
            index=models.Index(fields=['performance', 'session_date'], name='data_analys_perform_fdd323_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesession',
            index=models.Index(fields=['performance', 'round_number'], name='data_analys_perform_aa8f69_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['performance', 'status'], name='data_analys_perform_2174e4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdata',
            index=models.Index(fields=['status'], name='data_analys_status_34e620_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionseatgradesales',
            index=models.Index(fields=['session'], name='data_analys_session_d9b5ee_idx'),
        ),
    ]
