name: Create Admin User

on:
  workflow_dispatch:

env:
  PROJECT_ID: library-ai-agent-kr
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  create-admin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create admin user
      run: |
        python manage.py shell << EOF
        from django.contrib.auth.models import User
        from django.contrib.auth.hashers import make_password
        User.objects.create_superuser('admin', '', make_password('0315'))
        EOF 